### ISSUE TITLE
Some ERR!

### ISSUE THREAD

**Issue by Gary-CCCTS** [S1M0N38/soccerapi-server#3] opened 2021-03-05 16:24 UTC
[root@MyCloudServer ~]# docker run -it -p 5000:5000 s1m0n38/soccerapi
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/npm failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
[..................] - : WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
> soccerapi-server@0.0.1 start
> node index.js

Node.js web server at port 5000 is running.. stale data from https://registry.npmjs.org/ due to a request error during revalidation.
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106y.npmjs.org/ due to a request error during revalidation.
        return new Promise((fulfill) => (this._maximumTimer = setTimeout(fulfill, this._timeout))).then(() => new Errors_js_1.TimeoutError(errorMessage));
                                                                                                              ^

TimeoutError: Navigation timeout of 30000 ms exceeded
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.navigateFrame (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async file:///app/index.js:46:7
npm notice 
npm notice New patch version of npm available! 7.5.1 -> 7.5.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.5.2
npm notice Run npm install -g npm@7.5.2 to update!
npm notice 
npm ERR! code 1
npm ERR! path /app
npm ERR! command failed
npm ERR! command sh -c node index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-05T16_23_13_444Z-debug.log
[root@MyCloudServer ~]#

**Comment by S1M0N38** [comment] 2021-05-03 13:25
Duplicate of #5

**Closed as completed by S1M0N38** 2021-05-03 13:25 UTC
